In [0]:
import numpy as np

In [0]:
x = np.zeros([6,3])

In [397]:
x.reshape(3,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
c = np.array([[0,1,2], [3,4,5]])

In [0]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
len(c)

2

In [0]:
len(c[0])

3

In [0]:
c.shape

(2, 3)

In [0]:
type(c)

numpy.ndarray

In [0]:
c.tolist()

[[0, 1, 2], [3, 4, 5]]

In [0]:
c.min()

0

In [0]:
c[0] = [0,1,2]

In [0]:
c[1] = [3,4,5]

In [0]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c.max()

5

In [0]:
c.flatten()

array([0, 1, 2, 3, 4, 5])

In [0]:
c.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
c.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [0]:
c.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [0]:
a = np.arange(12)

In [0]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
a.shape

(12,)

In [0]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [0]:
a = a.reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
type(a)

numpy.ndarray

In [0]:
np.concatenate((a.T, c.T), axis=1)

array([[ 0,  3,  6,  9,  0,  3],
       [ 1,  4,  7, 10,  1,  4],
       [ 2,  5,  8, 11,  2,  5]])

In [0]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
c[0,2]

2

In [0]:
c.sum()

15

In [0]:
x = np.array([[1,2,2], [2,3,4], [2,5,6]])

In [401]:
np.argmax(x)

8

In [0]:
y = x[[0,1,2], [0,1,0]]

In [0]:
y

array([1, 4, 5])

In [0]:
y.shape

(3,)

In [0]:
x = np.arange(12)
x = x.reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
y = x[1:, [1,2]]
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [0]:
a = np.arange(10)
# a = a.reshape(5,2)

In [0]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [0]:
idx = np.array([True, False, True, False, True, False, True, False, True, False])
# idx = idx.reshape(5,2)

In [0]:
a[idx]

array([0, 2, 4, 6, 8])

In [0]:
x = np.array([[ 0, 1, 2],[ np.nan, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])

In [0]:
x

array([[ 0.,  1.,  2.],
       [nan,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [0]:
x[np.isnan(x)]

array([nan])

In [0]:
x[np.isnan(x)==False]

array([ 0.,  1.,  2.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([ 6.,  7.,  8.,  9., 10., 11.])

In [0]:
np.isnan(x)

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
x = np.array([[ 0, 1, 2],[ None, 4, 5],[ 6, 7, 8],[ 9, 10, 11]], dtype=np.float16)

In [0]:
x

array([[ 0.,  1.,  2.],
       [nan,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float16)

In [0]:
np.isnan(x)

array([[False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
x[np.isnan(x)] = 1

In [0]:
x

array([[ 0.,  1.,  2.],
       [ 1.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float16)

In [0]:
x.std()

3.613

In [0]:
x.var()

13.055

In [0]:
z = np.array([[1,3,5,7]])

In [0]:
len(z)

1

In [0]:
z.shape

(1, 4)

In [0]:
c = np.array([[0,1,2], [3,4,5]])

In [0]:
d = np.array([2,3,4])

In [0]:
c + d

array([[2, 4, 6],
       [5, 7, 9]])

In [0]:
np.dot(c, d)

array([11, 38])

In [0]:
c * d

array([[ 0,  3,  8],
       [ 6, 12, 20]])

In [0]:
c / d

array([[0.        , 0.33333333, 0.5       ],
       [1.5       , 1.33333333, 1.25      ]])

In [0]:
c - d

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [0]:
d - c

array([[ 2,  2,  2],
       [-1, -1, -1]])

In [0]:
d * c

array([[ 0,  3,  8],
       [ 6, 12, 20]])

In [0]:
d / c

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 3.        , 2.        ],
       [0.66666667, 0.75      , 0.8       ]])

In [0]:
d + c

array([[2, 4, 6],
       [5, 7, 9]])

In [0]:
np.max(c)

5

In [0]:
np.median(c * d)

7.0

In [0]:
np.sum(c)

15

In [0]:
c.ndim

2

In [0]:
x = np.array([1, 2, 3, 1])
x.sum(), x.max(), x.argmin(), x.argmax(), x.mean(), np.median(x), x.std()

(7, 3, 0, 2, 1.75, 1.5, 0.82915619758885)

In [0]:
x = np.array([[0, 1, 2], [7,8,9], [2, 3, 4], [4, 5, 6]])
x.sum(), x.max(), x.argmin(), x.argmax(), x.mean(), np.median(x), x.std()
# 0 1 2 2 3 4 4 5 6 7 8 9 


(51, 9, 0, 5, 4.25, 4.0, 2.7118566825454966)

In [0]:
x = np.array([[1,3,5,7], [2,4,6,8], [4,8,9,7]])
x, type(x)



(array([[1, 3, 5, 7],
        [2, 4, 6, 8],
        [4, 8, 9, 7]]), numpy.ndarray)

In [0]:
 x.ndim

2

In [0]:
x.shape

(3, 4)

In [0]:
len(x)

3

In [0]:
x[0]

array([1, 3, 5, 7])

In [0]:
x[:,3].sum()

22

In [0]:
x.sum(axis=1)

array([16, 20, 28])

In [0]:
x.sum(axis=0)

array([ 7, 15, 20, 22])

In [0]:
d = np.array([[[[4,5,6], [7,8,9], [1,5,6], [9,5,8]]], [[[4,5,6], [7,8,9], [1,5,6], [9,5,8]]]])

In [0]:
d

array([[[[4, 5, 6],
         [7, 8, 9],
         [1, 5, 6],
         [9, 5, 8]]],


       [[[4, 5, 6],
         [7, 8, 9],
         [1, 5, 6],
         [9, 5, 8]]]])

In [0]:
d.ndim

4

In [0]:
d.shape

(2, 1, 4, 3)

In [0]:
d.sum(axis=0)

array([[[ 8, 10, 12],
        [14, 16, 18],
        [ 2, 10, 12],
        [18, 10, 16]]])

In [0]:
d.sum(axis=1)

array([[[4, 5, 6],
        [7, 8, 9],
        [1, 5, 6],
        [9, 5, 8]],

       [[4, 5, 6],
        [7, 8, 9],
        [1, 5, 6],
        [9, 5, 8]]])

In [0]:
d.sum(axis=2)

array([[[21, 23, 29]],

       [[21, 23, 29]]])

In [0]:
d.sum(axis=3)

array([[[15, 24, 12, 22]],

       [[15, 24, 12, 22]]])

In [0]:
c.shape

(2, 3)

In [0]:
c.sum(axis=0)

array([3, 5, 7])

In [0]:
c.sum(axis=1)

array([ 3, 12])

In [0]:
student_score = [
[1, 90, 80, 85, 0, 0.0, 0],
[2, 90, 85, 90, 0, 0.0, 0],
[3, 80, 80, 80, 0, 0.0, 0]
]

student = np.array(student_score)

In [0]:
student.shape

(3, 7)

In [0]:
student[:, 4] = np.sum(student[:,1:4],axis=0)

In [0]:
student[:, 5] = np.mean(student[:,1:4],axis=0)

In [0]:
student

array([[  1.        ,  90.        ,  80.        ,  85.        ,
        260.        ,  86.66666667,   0.        ],
       [  2.        ,  90.        ,  85.        ,  90.        ,
        245.        ,  81.66666667,   0.        ],
       [  3.        ,  80.        ,  80.        ,  80.        ,
        255.        ,  85.        ,   0.        ]])

In [0]:
student[:, 1:4].mean(axis=1)

array([85.        , 88.33333333, 80.        ])

In [0]:
students_score = [
{'num':'1', 'name':'김철수','kor':90, 'eng':80, 'math':85},
{'num':'2', 'name':'박제동','kor':90, 'eng':85, 'math':90},
{'num':'3', 'name':'홍길동','kor':80,' eng':80, 'math':80}
]

In [0]:
from collections import Counter as cc

cnt = cc(cancer.data[:, 0]) # age_C데이터를 카운트한다.

print(cnt.most_common()[0]) # 상위 2개의 최빈값을 출력한다.