In [0]:
import numpy as np

In [0]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8], [9, 10]])

In [9]:
np.concatenate((a,b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [0]:
# np.concatenate((a,b), axis=1)

In [0]:
a = np.arange(9)
b = np.split(a,3)

In [12]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
b

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [15]:
type(b)

list

In [0]:
a = np.array([[1,2,3,], [4,5,6]])

In [21]:
np.insert(a,1,11, axis=1)

array([[ 1, 11,  2,  3],
       [ 4, 11,  5,  6]])

In [22]:
a = np.arange(12).reshape(3,4)
a, np.delete(a,5), np.delete(a,1,axis = 1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  2,  3],
        [ 4,  6,  7],
        [ 8, 10, 11]]))

In [26]:
np.delete(a,[7,8,9])

array([ 0,  1,  2,  3,  4,  5,  6, 10, 11])

In [47]:
student_scores_high = np.random.randint(low = 80, high=100, size =(30, 3)) 
student_scores_middle = np.random.randint(low = 50, high=79, size =(20, 3)) 
student_scores_low = np.random.randint(low = 0, high=49, size =(100, 3)) 
student_scores_high

array([[95, 81, 92],
       [87, 96, 84],
       [90, 84, 93],
       [93, 83, 99],
       [84, 87, 84],
       [96, 85, 80],
       [95, 85, 89],
       [83, 88, 80],
       [90, 82, 86],
       [96, 94, 94],
       [84, 94, 88],
       [92, 86, 90],
       [94, 88, 99],
       [81, 98, 88],
       [85, 99, 94],
       [96, 99, 92],
       [97, 96, 82],
       [88, 92, 98],
       [82, 99, 97],
       [82, 94, 86],
       [94, 83, 83],
       [99, 98, 84],
       [90, 87, 82],
       [92, 85, 91],
       [88, 86, 96],
       [86, 96, 96],
       [90, 81, 93],
       [86, 91, 96],
       [94, 90, 94],
       [94, 94, 98]])

In [0]:
student_scores = np.insert(student_scores, 0, student_scores_middle, axis=0)
student_scores = np.insert(student_scores_high, 0, student_scores_low, axis=0)

In [45]:
len(student_scores)

130

In [46]:
student_scores

array([[34, 16, 41],
       [ 7,  9, 13],
       [14, 30, 11],
       [37, 19, 35],
       [23, 48, 14],
       [35, 29,  4],
       [ 4, 41, 24],
       [28, 14, 25],
       [ 6,  7, 27],
       [10, 12, 38],
       [13, 34, 32],
       [10, 41, 29],
       [15, 47, 18],
       [40, 39, 29],
       [38, 38,  3],
       [17, 24, 26],
       [11, 13, 36],
       [ 7, 10, 23],
       [31, 29, 28],
       [ 1, 39, 34],
       [ 6, 19, 10],
       [38, 31, 33],
       [12, 43, 12],
       [26,  8, 36],
       [40, 18,  8],
       [24, 47, 20],
       [28,  1, 47],
       [ 6, 34, 11],
       [42, 31, 12],
       [46, 48,  5],
       [33,  0, 41],
       [10, 34, 48],
       [10, 24, 10],
       [26, 40, 39],
       [ 4, 11, 12],
       [14, 48, 46],
       [16, 22,  9],
       [13,  6, 45],
       [23,  9, 36],
       [45, 24, 26],
       [29, 34,  3],
       [39, 10, 15],
       [33,  7,  9],
       [41,  0, 22],
       [33, 43,  0],
       [44, 21,  5],
       [ 2,  4, 20],
       [39, 4