In [0]:
import numpy as np

In [0]:
a = np.array([[1,2,3], [1,0,-1], [4,5,6]])
b = np.array([[-1,1], [3,2], [-2,5]])

In [4]:
np.dot(a,b)

array([[-1, 20],
       [ 1, -4],
       [-1, 44]])

In [0]:
student_score = [
 [1, 90, 80, 85, 0, 0.0, 0, 0],
 [2, 88, 85, 90, 0, 0.0, 0, 0],
 [3, 32, 85, 90, 0, 0.0, 0, 0],
 [4, 42, 75, 93, 0, 0.0, 0, 0],
 [5, 82, 86, 88, 0, 0.0, 0, 0]
]
ndarray = np.array(student_score)


In [8]:
ndarray, type(ndarray), type(ndarray[0])

(array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
        [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
        [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
        [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
        [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]]),
 numpy.ndarray,
 numpy.ndarray)

In [9]:
ndarray[:, 0]

array([1., 2., 3., 4., 5.])

In [12]:
ndarray[4, :]

array([ 5., 82., 86., 88.,  0.,  0.,  0.,  0.])

In [13]:
ndarray[:, 1:4]

array([[90., 80., 85.],
       [88., 85., 90.],
       [32., 85., 90.],
       [42., 75., 93.],
       [82., 86., 88.]])

In [14]:
ndarray == 0

array([[False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True]])

In [15]:
ndarray[:,1:5] > 20

array([[ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True, False],
       [ True,  True,  True, False]])

In [16]:
(ndarray[:,1:5] > 20) & (ndarray[:,1:5] > 80)

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True,  True, False],
       [False, False,  True, False],
       [ True,  True,  True, False]])

In [17]:
ndarray[ndarray == 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [21]:
ndarray[:,1:5][ndarray[:,1:5] > 20]

array([90., 80., 85., 88., 85., 90., 32., 85., 90., 42., 75., 93., 82.,
       86., 88.])

In [25]:
ndarray

array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
       [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
       [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
       [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
       [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]])

In [26]:
np.insert(ndarray, 0, [1,2,3,4,5,6,7,8], axis = 0)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
       [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
       [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
       [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
       [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]])

In [0]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame(wine.data, columns=wine.feature_names)
sy = pd.Series(wine.target, dtype="category")
sy = sy.cat.rename_categories(wine.target_names)
df['class'] = sy

In [0]:
sns.pairplot(vars=["alcohol", "alcalinity_of_ash", "total_phenols", "flavanoids"], 
             hue="class", data=df)
plt.show()