# preprocessing

In [0]:
import pandas as pd
import os

In [0]:
os.getcwd()

'/content'

In [0]:
os.chdir('/content/drive/My Drive/Colab Notebooks/project/good/test')

In [0]:
os.chdir('../')

In [0]:
abs_dir = os.path.join(os.getcwd())

In [0]:
abs_dir

'/content/drive/My Drive/Colab Notebooks/project/good/test'

In [0]:
file_nms = os.listdir(abs_dir)

In [0]:
file_nms = [i for i in os.listdir()]

In [0]:
for i in file_nms:
  print(i)

11.1인당_도시지역면적_현황_시도_시_군_구__20200420094650.csv
12.인구_천명당_범죄발생건수_시도__20200420102407.csv
10.비만율_시도_시_군_구__20200420094536.csv
01.삶의_만족도_시도__20200420093522.csv
04.미세먼지_PM10__월별_도시별_대기오염도_20200420092908.csv
03.행정구역_시도_별_1인당_지역내총생산__지역총소득__개인소득_20200420092743.csv
05.근로여건만족도_시도__20200420093430.csv
06.녹지환경_만족도_시도__20200420093500.csv
09.음주율_시도_시_군_구__20200420094256.csv
08.기부율_시도__20200420094148.csv
02.지역별_학생·학습자_현황_20200420092656.csv
07.인구십만명당_자살률_시도_시_군_구__20200420094104.csv
test
14.소득만족도_시도__20200420134335.csv


In [0]:
df = pd.read_csv('06.녹지환경_만족도_시도__20200420093500.csv', encoding='CP949', header=1, index_col=0)
df.head()

특성별(1) 특성별(2)      계  매우 좋다  약간 좋다    보통  약간 나쁘다  매우 나쁘다
행정구역별(1)                                                         
서울           전체      계  100.0   13.0   32.8  37.3    13.3     3.6
부산           전체      계  100.0   14.5   35.1  38.1    10.6     1.6
대구           전체      계  100.0    6.5   30.5  47.8    12.2     3.0
인천           전체      계  100.0   12.2   28.1  41.1    14.5     4.1
광주           전체      계  100.0   11.1   36.1  41.8     9.3     1.6

In [0]:
df.to_csv('./test/earningg')

In [0]:
df.columns

Index(['계', '매우 만족', '약간 만족', '보통', '약간 불만족', '매우 불만족'], dtype='object')

In [0]:
df.index

Index(['전국', '서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시',
       '세종특별자치시', '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도', '경상남도',
       '제주특별자치도'],
      dtype='object', name='행정구역별(1)')

In [0]:
df_sat = df

In [0]:
df_stu = df

In [0]:
df_ear = df

In [0]:
df_dus = df

In [0]:
df_job = df

In [0]:
df_env = df

In [0]:
df_sui = df

In [0]:
df_don = df

In [0]:
df_dri = df

In [0]:
df_fat = df

In [0]:
df_cri = df

In [0]:
df_ter = df

In [0]:
os.chdir('./test')

In [0]:
df_env.to_csv('./enviroment1')

In [0]:
df_sat.to_csv('./satisfaction')
df_stu.to_csv('./study')
df_ear.to_csv('./earning')
df_dus.to_csv('./dust')
df_job.to_csv('./job')
df_sui.to_csv('./suicide')
df_don.to_csv('./donnation')
df_dri.to_csv('./drink')
df_fat.to_csv('./fat')
df_cri.to_csv('./crime')
df_ter.to_csv('./land')

# 불러오기

In [0]:
os.chdir('./test')

In [0]:
file_nms = [i for i in os.listdir()]

In [0]:
file_nms

['satisfaction',
 'study',
 'earning',
 'dust',
 'job',
 'enviroment',
 'suicide',
 'donnation',
 'drink',
 'fat',
 'crime',
 'land',
 'earningg',
 'enviroment1']

In [0]:
df_sat = pd.read_csv(file_nms[0], index_col=0)
df_sat.head()

계  매우 만족  약간 만족    보통  약간 불만족  매우 불만족
행정구역별(1)                                           
서울특별시     100.0   14.1   26.5  42.0    13.0     4.4
부산광역시     100.0    9.9   23.9  47.3    15.5     3.4
대구광역시     100.0   11.6   22.9  47.0    15.5     3.1
인천광역시     100.0   17.1   26.5  40.8    11.9     3.6
광주광역시     100.0   16.7   24.1  43.7    11.1     4.5

In [0]:
df_sat['total'] = df_sat['매우 만족'] + df_sat['약간 만족'] + df_sat['보통'] - df_sat['매우 불만족'] - df_sat['약간 불만족']
df_sat.head()
df_sat1 = df_sat['total']

In [0]:
df_ear = pd.read_csv(file_nms[-1], index_col=0)
df_ear.head()
df_ear.columns = ['계', '소득있음', '매우 만족', '약간 만족', '보통', '약간 불만족', '매우 불만족']

In [0]:
df_ear['total'] = df_ear['매우 만족'] + df_ear['약간 만족'] + df_ear['보통'] - df_ear['매우 불만족'] - df_ear['약간 불만족']

In [0]:
df_ear1 = df_ear[['total']]
df_ear1.columns = ['earning_total']

In [0]:
df_job = pd.read_csv(file_nms[4], index_col=0)
df_job['total'] = df_job['매우 만족']
df_job.head()
df_job1 = df_job[['total']]
df_job1.columns = ['job_total']

In [0]:
df_env = pd.read_csv('enviroment1', index_col=0)
df_env
df_env['total'] = df_env['매우 좋다'] + df_env['약간 좋다'] + df_env['보통'] - df_env['매우 나쁘다'] - df_env['약간 나쁘다']
df_env1 = df_env[['total']]
df_env1.columns = ['env_total']

In [0]:
df_env1

In [0]:
df_sui = pd.read_csv(file_nms[6], index_col=0)

In [0]:
df_sui['mean'] = (df_sui['2016'] + df_sui['2017'] + df_sui['2018'])/3

In [0]:
df_sui1 = df_sui[['mean']]
df_sui1.columns = ['suicide_mean']

In [0]:
df_sui1

In [0]:
df_don = pd.read_csv(file_nms[7], index_col=0)
df_don.head()
df_don = df_don[['2019']]
df_don.columns = ['donnation']

In [0]:
df_dri = pd.read_csv(file_nms[8], index_col=0)
df_dri['mean'] = (df_dri['2016'] + df_dri['2017'] + df_dri['2018'])/3

df_dri1 = df_dri[['mean']]
df_dri1.columns = ['drink_mean']

In [0]:
df_fat = pd.read_csv(file_nms[9], index_col=0)
df_fat['mean'] = (df_fat['2016'] + df_fat['2017'] + df_fat['2018'])/3
df_fat.head()
df_fat1 = df_fat[['mean']]
df_fat1.columns = ['fat_mean']

In [0]:
df_crime = pd.read_csv(file_nms[10], names = ['인구 천명당 범죄발생건수', '범죄발생건수', '주민등록인구'])
df_crime = df_crime[1:]
df_crime1 = df_crime['인구 천명당 범죄발생건수']

In [0]:
df_land = pd.read_csv(file_nms[11], index_col=0)
# mean(df_land, '2016', '2017', '2018')
# df_land = df_land[1:]
df_land.head()

도시지역 인구      도시지역 면적  1인당면적 주+상+공  1인당면적 녹지지역
행정구역별                                                 
서울특별시  9765623.0  605569314.0        37.96       24.05
부산광역시  3441453.0  940825058.0        67.91      158.72
대구광역시  2456722.0  797919337.0        73.44      251.35
인천광역시  2887841.0  579740346.0        71.68       99.61
광주광역시  1459336.0  480053767.0        83.11      245.84

In [0]:
df_env1.index = df_sat1.index
df_env1

env_total
행정구역별(1)           
서울특별시          66.2
부산광역시          75.5
대구광역시          69.6
인천광역시          62.8
광주광역시          78.1
대전광역시          75.2
울산광역시          72.0
세종특별자치시        79.5
경기도            79.0
강원도            90.2
충청북도           76.2
충청남도           79.2
전라북도           77.6
전라남도           88.6
경상북도           79.7
경상남도           83.8
제주특별자치도        84.2

In [0]:
df_sat1, df_ear1, df_job1, df_fat1, df_land, df_crime1, df_dri1, df_don, df_sui1, df_env1

In [0]:
df_ear1

행정구역별(1)
서울특별시       8.7
부산광역시       6.4
대구광역시       7.8
인천광역시      14.8
광주광역시      18.9
대전광역시       7.8
울산광역시       7.2
세종특별자치시    25.8
경기도        13.7
강원도        19.8
충청북도       14.0
충청남도       19.5
전라북도       13.0
전라남도       22.6
경상북도       11.2
경상남도       18.2
제주특별자치도    19.4
Name: total, dtype: float64

In [2]:
df_all = pd.concat([df_sat1, df_ear1, df_job1, df_fat1, df_land, df_crime1, df_dri1, df_don, df_sui1, df_env1], axis=1)

NameError: ignored

In [1]:
df_all

NameError: ignored

In [0]:
df_all = df_all.sort_values(ascending=False, by='total')

In [0]:
df_all['인구 천명당 범죄발생건수'] = df_all['인구 천명당 범죄발생건수'].fillna(0)

In [0]:
df_all['인구 천명당 범죄발생건수'] = df_all['인구 천명당 범죄발생건수'].astype('float')

In [0]:
df_all.iloc[0,8] = 27.800000 # 25%

In [0]:
df_all.describe(include='all')

total  earning_total  job_total  ...  donnation  suicide_mean  env_total
count  17.000000      17.000000  17.000000  ...  17.000000     17.000000  17.000000
mean   68.494118      14.635294   6.541176  ...  25.800000     26.778431  77.494118
std     4.859973       5.913855   1.396898  ...   3.362663      3.126054   7.206115
min    62.200000       6.400000   4.300000  ...  19.300000     22.266667  62.800000
25%    65.300000       8.700000   5.400000  ...  23.700000     25.000000  75.200000
50%    67.600000      14.000000   6.700000  ...  25.600000     27.000000  78.100000
75%    71.100000      19.400000   6.800000  ...  28.300000     28.133333  79.700000
max    82.600000      25.800000   9.700000  ...  32.800000     33.100000  90.200000

[8 rows x 13 columns]

In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()


In [0]:
df_all[:] = scaler.fit_transform(df_all[:])

In [0]:
df_all

In [0]:
df_all.describe()

total  earning_total  job_total  ...  donnation  suicide_mean  env_total
count  17.000000      17.000000  17.000000  ...  17.000000     17.000000  17.000000
mean    0.308535       0.424500   0.415033  ...   0.481481      0.416471   0.536282
std     0.238234       0.304838   0.258685  ...   0.249086      0.288559   0.262997
min     0.000000       0.000000   0.000000  ...   0.000000      0.000000   0.000000
25%     0.151961       0.118557   0.203704  ...   0.325926      0.252308   0.452555
50%     0.264706       0.391753   0.444444  ...   0.466667      0.436923   0.558394
75%     0.436275       0.670103   0.462963  ...   0.666667      0.541538   0.616788
max     1.000000       1.000000   1.000000  ...   1.000000      1.000000   1.000000

[8 rows x 13 columns]

# torch

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [0]:
model = nn.Linear(10,1)

In [0]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.1) 

In [0]:
df_all.iloc[:,1:].values.tolist()

In [0]:
# 데이터
x_train = torch.FloatTensor(df_all.iloc[:,1:].values.tolist())
y_train = torch.FloatTensor(df_all.iloc[:,0:1].values.tolist())


In [0]:
y_train

In [0]:
model = nn.Linear(12,1)
model(x_train)

tensor([[0.2793],
        [0.3693],
        [0.0396],
        [0.3086],
        [0.3977],
        [0.2683],
        [0.2783],
        [0.2807],
        [0.6088],
        [0.7519],
        [0.2865],
        [0.3427],
        [0.4865],
        [0.2535],
        [0.2991],
        [0.2059],
        [0.2720]], grad_fn=<AddmmBackward>)

In [0]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 20000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/20000 Cost: 0.086763
Epoch  100/20000 Cost: 0.086763
Epoch  200/20000 Cost: 0.086763
Epoch  300/20000 Cost: 0.086763
Epoch  400/20000 Cost: 0.086763
Epoch  500/20000 Cost: 0.086763
Epoch  600/20000 Cost: 0.086763
Epoch  700/20000 Cost: 0.086763
Epoch  800/20000 Cost: 0.086763
Epoch  900/20000 Cost: 0.086763
Epoch 1000/20000 Cost: 0.086763
Epoch 1100/20000 Cost: 0.086763
Epoch 1200/20000 Cost: 0.086763
Epoch 1300/20000 Cost: 0.086763
Epoch 1400/20000 Cost: 0.086763
Epoch 1500/20000 Cost: 0.086763
Epoch 1600/20000 Cost: 0.086763
Epoch 1700/20000 Cost: 0.086763
Epoch 1800/20000 Cost: 0.086763
Epoch 1900/20000 Cost: 0.086763
Epoch 2000/20000 Cost: 0.086763
Epoch 2100/20000 Cost: 0.086763
Epoch 2200/20000 Cost: 0.086763
Epoch 2300/20000 Cost: 0.086763
Epoch 2400/20000 Cost: 0.086763
Epoch 2500/20000 Cost: 0.086763
Epoch 2600/20000 Cost: 0.086763
Epoch 2700/20000 Cost: 0.086763
Epoch 2800/20000 Cost: 0.086763
Epoch 2900/20000 Cost: 0.086763
Epoch 3000/20000 Cost: 0.086763
Epoch 31

In [0]:
print(list(model.parameters()))


[Parameter containing:
tensor([[-0.0093,  0.1846,  0.2411,  0.1773, -0.0939, -0.2419, -0.0437,  0.2681,
         -0.1398, -0.0826,  0.1234,  0.2830]], requires_grad=True), Parameter containing:
tensor([0.1269], requires_grad=True)]
